// Code generated by "gen-const -type HttpCode"; DO NOT EDIT.
// 代码文件由 "gen-const -type HttpCode" 生成; 不要编辑本代码文件。

package exp

import "fmt"

type HttpCodeType struct {
	Val int
	Msg string
}

func (receiver *HttpCodeType) GetVal() int {
	return receiver.Val
}

func (receiver *HttpCodeType) GetMsg() string {
	return receiver.Msg
}

func HttpCodeFunc(val int, msg string) *HttpCodeType {
	return &HttpCodeType{
		Val: val,
		Msg: msg,
	}
}

func (receiver *HttpCodeType) String() string {
	return "HttpCodeType (Val: " + fmt.Sprintf("%+v", receiver.Val) + ", Msg: " + receiver.Msg + ")"
}

var (
	RespOkHttpCode   = HttpCodeFunc(0, "成功")
	RespFailHttpCode = HttpCodeFunc(500, "失败")
)
