// Code generated by "gen-const -type HttpCodeStr"; DO NOT EDIT.
// 代码文件由 "gen-const -type HttpCodeStr" 生成; 不要编辑本代码文件。

package exp

type HttpCodeStrType struct {
	Val string
	Msg string
}

func (receiver *HttpCodeStrType) GetVal() string {
	return receiver.Val
}

func (receiver *HttpCodeStrType) GetMsg() string {
	return receiver.Msg
}

func HttpCodeStrFunc(val string, msg string) *HttpCodeStrType {
	return &HttpCodeStrType{
		Val: val,
		Msg: msg,
	}
}

func (receiver *HttpCodeStrType) String() string {
	return "HttpCodeStrType (Val: " + receiver.Val + ", Msg: " + receiver.Msg + ")"
}

var (
	RespOkStrHttpCodeStr   = HttpCodeStrFunc("0", "成功")
	RespFailStrHttpCodeStr = HttpCodeStrFunc("500", "失败")
)
