// Code generated by "gen-const -type HttpCodeBool"; DO NOT EDIT.
// 代码文件由 "gen-const -type HttpCodeBool" 生成; 不要编辑本代码文件。

package exp

import "fmt"

type HttpCodeBoolType struct {
	Val bool
	Msg string
}

func (receiver *HttpCodeBoolType) GetVal() bool {
	return receiver.Val
}

func (receiver *HttpCodeBoolType) GetMsg() string {
	return receiver.Msg
}

func HttpCodeBoolFunc(val bool, msg string) *HttpCodeBoolType {
	return &HttpCodeBoolType{
		Val: val,
		Msg: msg,
	}
}

func (receiver *HttpCodeBoolType) String() string {
	return "HttpCodeBoolType (Val: " + fmt.Sprintf("%+v", receiver.Val) + ", Msg: " + receiver.Msg + ")"
}

var (
	RespOkBoolHttpCodeBool   = HttpCodeBoolFunc(true, "成功")
	RespFailBoolHttpCodeBool = HttpCodeBoolFunc(false, "失败")
)
