// Code generated by "gen-const -type Num"; DO NOT EDIT.
// 代码文件由 "gen-const -type Num" 生成; 不要编辑本代码文件。

package exp

import "fmt"

type NumType struct {
	Val int
	Msg string
}

func (receiver *NumType) GetVal() int {
	return receiver.Val
}

func (receiver *NumType) GetMsg() string {
	return receiver.Msg
}

func NumFunc(val int, msg string) *NumType {
	return &NumType{
		Val: val,
		Msg: msg,
	}
}

func (receiver *NumType) String() string {
	return "NumType (Val: " + fmt.Sprintf("%+v", receiver.Val) + ", Msg: " + receiver.Msg + ")"
}

var (
	NumStartNum = NumFunc(0, "start")
	NumANum     = NumFunc(1, "A")
	NumBNum     = NumFunc(2, "B")
	NumCNum     = NumFunc(3, "C")
	NumDNum     = NumFunc(4, "D")
	NumENum     = NumFunc(5, "E")
)
